const http=require("http");const {Client,GatewayIntentBits}=require("discord.js");const config=require("./config");const agent=require("./agent");const controller=require("./controller");
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent]});
const allowed=id=>!config.allowedChannelIds.length||config.allowedChannelIds.includes(id);const canControl=m=>!config.adminIds.length&&!config.controlRoleIds.length||config.adminIds.includes(m.id)||m.roles.cache.some(r=>config.controlRoleIds.includes(r.id));
const uptime=s=>s==null?"—":`${Math.floor(s/60)}m ${s%60}s`;const format=s=>[`**SMC status**`,`Codespace: **${s.codespace}**`,`Agent: **${s.agent}**`,`Minecraft: **${s.minecraft}**`,`Playit: **${s.playit}**`,`Players: **${s.players??"—"}/${s.maxPlayers??"—"}**`,`Uptime: **${uptime(s.uptimeSec)}**`,s.error?`Error: \`${s.error}\``:null,`Address: **${config.host}:${config.port}**`].filter(Boolean).join("\n");
async function progress(message,text){await message.edit(`🟡 **SMC**\n${text}`).catch(()=>{});}
async function handle(message,parts){const command=(parts[1]||"help").toLowerCase();if(command==="status")return message.reply(format(await controller.liveStatus()));if(command==="help")return message.reply(["**SMC commands**","`smc start` — start Minecraft","`smc stop` — stop Minecraft and Codespace","`smc restart` — restart Minecraft","`smc status` — live status","`smc whitelist add <username>` — whitelist a player"].join("\n"));if(!canControl(message.member))return message.reply("⚠️ You do not have permission to control SMC.");if(command==="whitelist"&&parts[2]?.toLowerCase()==="add"){if(!parts[3])return message.reply("Usage: `smc whitelist add <username>`");const r=controller.whitelistAdd(parts[3]);return message.reply(`🟡 Whitelist request queued for **${r.name}**.`);}if(!["start","stop","restart"].includes(command))return message.reply("Unknown command. Use `smc help`.");const out=await message.reply(command==="start"?"🟡 Starting SMC…":command==="stop"?"🟡 Stopping SMC…":"🟡 Restarting SMC…");try{const r=command==="start"?await controller.startServer(t=>progress(out,t)):command==="stop"?await controller.stopServer(t=>progress(out,t)):await controller.restartServer(t=>progress(out,t));await out.edit(command==="stop"?"🔴 **SMC stopped.**":`🟢 **SMC online.**\n${format(r)}`).catch(()=>{});}catch(e){await out.edit(`⚠️ **SMC operation failed**\n\`${String(e.message||e).replace(/`/g,"'")}\``).catch(()=>{});}}
client.on("messageCreate",async message=>{if(message.author.bot||!message.guild||!allowed(message.channelId))return;const parts=message.content.trim().split(/\s+/);if(parts[0]?.toLowerCase()!=="smc")return;try{await handle(message,parts);}catch(e){await message.reply(`⚠️ ${e.message||"SMC request failed."}`).catch(()=>{});}});
const json=(res,status,data)=>{res.writeHead(status,{"Content-Type":"application/json","Cache-Control":"no-store"});res.end(JSON.stringify(data));};const server=http.createServer((req,res)=>{if(req.method==="GET"&&(req.url==="/"||req.url==="/health"))return json(res,200,{ok:true,operation:controller.operation(),agent:agent.info()});if(req.method!=="POST"||req.url!=="/agent/sync")return json(res,404,{error:"not_found"});if(!agent.authenticated(req))return json(res,401,{error:"unauthorized"});let body="";req.on("data",c=>{body+=c;if(body.length>1048576)req.destroy();});req.on("end",()=>{try{return json(res,200,agent.sync(JSON.parse(body||"{}").status));}catch(e){return json(res,400,{error:e.message||"invalid_request"});}});});
server.listen(config.httpPort,"0.0.0.0",()=>console.log(`SMC control plane listening on ${config.httpPort}`));client.once("ready",()=>console.log(`Discord connected as ${client.user.tag}`));client.login(config.discordToken).catch(e=>{console.error("Discord login failed:",e);process.exit(1);});
