const http=require("http");const {Client,GatewayIntentBits}=require("discord.js");const config=require("./config");const agent=require("./agent");const controller=require("./controller");
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent]});
const allowed=id=>!config.allowedChannelIds.length||config.allowedChannelIds.includes(id);const canControl=m=>!config.adminIds.length&&!config.controlRoleIds.length||config.adminIds.includes(m.id)||m.roles.cache.some(r=>config.controlRoleIds.includes(r.id));
const lines={start:["🚀 Ignition sequence engaged.","⚡ Bringing the world online.","🎮 Your server is waking up."],stop:["🛑 Powering the world down cleanly.","🌙 Putting the server to sleep.","🔒 Securing the world before shutdown."],restart:["🔄 Fresh cycle incoming.","⚡ Resetting the world, keeping the momentum.","♻️ Giving the server a clean second wind."],online:["🔥 The world is live. Make it count.","🟢 We're in business. Your world is ready.","⚔️ Server online. Adventure awaits."],stopped:["🌙 The world is safely asleep.","🔴 Server offline. Nothing is running behind the scenes.","🛌 Shutdown complete. Until next time."],status:["📡 Here's the pulse of your server.","🛰️ Live telemetry incoming.","👀 Current server pulse:"],error:["💥 The sequence hit a snag.","⚠️ Something interrupted the mission.","🧩 The server hit a bump; here's what happened."],help:["🎮 Your SMC command deck:","🛠️ Your server controls:","⚡ Quick commands, zero fuss:"]};
const pick=k=>lines[k][Math.floor(Math.random()*lines[k].length)];const uptime=s=>s==null?"—":`${Math.floor(s/60)}m ${s%60}s`;
const format=s=>{const address=s.publicAddress||"Not available yet";return [`**SMC status**`,pick("status"),`Codespace: **${s.codespace}**`,`Agent: **${s.agent}**`,`Minecraft: **${s.minecraft}**`,`Playit: **${s.playit}**`,`Players: **${s.players??"—"}/${s.maxPlayers??"—"}**`,`Uptime: **${uptime(s.uptimeSec)}**`,`Address: **${address}**`,s.error?`Error: \`${s.error}\``:null].filter(Boolean).join("\n");};
async function progress(message,text){await message.edit(`🟡 **SMC**\n${text}\n\n${pick("status")}`).catch(()=>{});}
async function handle(message,parts){const command=(parts[1]||"help").toLowerCase();if(command==="status")return message.reply(format(await controller.liveStatus()));if(command==="help")return message.reply([`**SMC commands**`,pick("help"),"`smc start` — start Minecraft","`smc stop` — stop Minecraft and Codespace","`smc restart` — restart Minecraft","`smc status` — live status","`smc whitelist add <username>` — whitelist a player"].join("\n"));if(!canControl(message.member))return message.reply(`⚠️ ${pick("error")}\nYou do not have permission to control SMC.`);if(command==="whitelist"&&parts[2]?.toLowerCase()==="add"){if(!parts[3])return message.reply("Usage: `smc whitelist add <username>`");const r=controller.whitelistAdd(parts[3]);return message.reply(`🟡 ${pick("status")}\nWhitelist request queued for **${r.name}**.`);}if(!["start","stop","restart"].includes(command))return message.reply(`⚠️ ${pick("error")}\nUnknown command. Use \`smc help\`.`);const out=await message.reply(`🟡 ${pick(command)}\nHang tight — SMC is on it.`);try{const r=command==="start"?await controller.startServer(t=>progress(out,t)):command==="stop"?await controller.stopServer(t=>progress(out,t)):await controller.restartServer(t=>progress(out,t));await out.edit(command==="stop"?`🔴 **SMC stopped.**\n${pick("stopped")}`:`🟢 **SMC online.**\n${pick("online")}\n\n${format(r)}`).catch(()=>{});}catch(e){await out.edit(`⚠️ **SMC operation failed**\n${pick("error")}\n\`${String(e.message||e).replace(/`/g,"'")}\``).catch(()=>{});}}
client.on("messageCreate",async message=>{if(message.author.bot||!message.guild||!allowed(message.channelId))return;const parts=message.content.trim().split(/\s+/);if(parts[0]?.toLowerCase()!=="smc")return;try{await handle(message,parts);}catch(e){await message.reply(`⚠️ ${pick("error")}\n${e.message||"SMC request failed."}`).catch(()=>{});}});
const json=(res,status,data)=>{res.writeHead(status,{"Content-Type":"application/json","Cache-Control":"no-store"});res.end(JSON.stringify(data));};const server=http.createServer((req,res)=>{if(req.method==="GET"&&(req.url==="/"||req.url==="/health"))return json(res,200,{ok:true,operation:controller.operation(),agent:agent.info()});if(req.method!=="POST"||req.url!=="/agent/sync")return json(res,404,{error:"not_found"});if(!agent.authenticated(req))return json(res,401,{error:"unauthorized"});let body="";req.on("data",c=>{body+=c;if(body.length>1048576)req.destroy();});req.on("end",()=>{try{return json(res,200,agent.sync(JSON.parse(body||"{}").status));}catch(e){return json(res,400,{error:e.message||"invalid_request"});}});});
server.listen(config.httpPort,"0.0.0.0",()=>console.log(`SMC control plane listening on ${config.httpPort}`));client.once("ready",()=>console.log(`Discord connected as ${client.user.tag}`));client.login(config.discordToken).catch(e=>{console.error("Discord login failed:",e);process.exit(1);});
